repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        args: ["--check"]
        language: system
      - id: black
        name: black
        entry: black
        args: ["--check"]
        types: [python]
        language: system
      - id: flake8
        name: flake8
        entry: flake8
        args: []
        types: [python]
        language: system
      - id: mypy
        name: mypy
        entry: mypy
        args: ["--check"]
        types: [python]
        language: system
      - id: pytest
        name: pytest
        entry: pytest
        args: ["--cov=torch_simple", "--cov-report=term-missing", "tests", "--doctest-glob=*.py"]
        language: system
        pass_filenames: false
